version: '3'

services:
  api:
    container_name: coding-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_DB_HOST: mysql
      API_DB_NAME: coding-challenge-api
      API_DB_DEV_NAME: coding-challenge-api-dev
      API_DB_TEST_NAME: coding-challenge-api-test
      API_DB_PASSWORD: M9S8TsR7z7SG6Y
    ports:
      - "3000:3000"
    links:
      - mysql
    volumes:
      - ${PWD}:/opt/coding-challenge-api
    command: /bin/bash -c "sleep 25; rake db:drop db:create db:migrate && rails server -b 0.0.0.0"
  mysql:
    container_name: coding-challenge-mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_DATABASE: coding-challenge-api
      MYSQL_ROOT_PASSWORD: M9S8TsR7z7SG6Y
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci "
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9201:9201"
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
networks:
  esnet:

