name: funny comment 
on:
  pull_request:
  issues: 
    types: [opened]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: Marta83/funny-comment-action@v1
        id: comment
        with:
          comment_type: all
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}